# Automatically generated by: ros2nix --flake --distro humble
{
  lib,
  buildRosPackage,
  ackermann-msgs,
  ament-copyright,
  ament-flake8,
  ament-pep257,
  f1tenth-gym,
  foxglove-bridge,
  geometry-msgs,
  joint-state-publisher,
  launch,
  launch-ros,
  nav-msgs,
  nav2-lifecycle-manager,
  nav2-map-server,
  python3Packages,
  rclpy,
  robot-state-publisher,
  rviz2,
  sensor-msgs,
  teleop-twist-keyboard,
  tf2-ros,
  xacro,
}:
buildRosPackage rec {
  pname = "ros-humble-f1tenth-gym-ros";
  version = "0.0.0";

  src = ./.;
  patches = [ ./0001-fix-tempdir.patch ];

  buildType = "ament_python";
  checkInputs = [
    ament-copyright
    ament-flake8
    ament-pep257
    python3Packages.pytest
  ];
  propagatedBuildInputs = [
    f1tenth-gym
    ackermann-msgs
    foxglove-bridge
    geometry-msgs
    joint-state-publisher
    launch
    launch-ros
    nav-msgs
    nav2-lifecycle-manager
    nav2-map-server
    python3Packages.scipy
    rclpy
    robot-state-publisher
    rviz2
    sensor-msgs
    teleop-twist-keyboard
    tf2-ros
    xacro
  ];

  meta = {
    description = "Bridge for using f1tenth_gym in ROS2";
    license = with lib.licenses; [ mit ];
  };
}
